# Generated by Django 6.0.2 on 2026-02-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personagem',
            new_name='Personagens',
        ),
    ]
