# Generated by Django 6.0.2 on 2026-02-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0002_rename_personagem_personagens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personagens',
            options={'verbose_name': 'Personagem', 'verbose_name_plural': 'Personagens'},
        ),
        migrations.AddField(
            model_name='personagens',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
