# Generated by Django 6.0.2 on 2026-02-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personagem', '0003_alter_personagens_options_personagens_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagens',
            name='classe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='personagens',
            name='experiencia',
            field=models.IntegerField(default=0, verbose_name='XP'),
        ),
        migrations.AddField(
            model_name='personagens',
            name='nivel',
            field=models.IntegerField(default=1, verbose_name='Nível'),
        ),
        migrations.AddField(
            model_name='personagens',
            name='raca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raça'),
        ),
        migrations.AddField(
            model_name='personagens',
            name='sistema',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema de RPG'),
        ),
        migrations.AddField(
            model_name='personagens',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='personagens',
            name='banner',
            field=models.ImageField(blank=True, help_text='Imagem de banner (opcional). Recomendado: 1200x400px', null=True, upload_to='personagens/banners/', verbose_name='Banner do Personagem'),
        ),
        migrations.AlterField(
            model_name='personagens',
            name='body',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='personagens',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='personagens',
            name='title',
            field=models.CharField(max_length=75, verbose_name='Nome do Personagem'),
        ),
    ]
